name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform-validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario: [open-ssh, missing-tags, public-s3, idle-compute]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        working-directory: terraform-lab/${{ matrix.scenario }}
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform-lab/${{ matrix.scenario }}
        run: terraform validate

      - name: Terraform Format Check
        working-directory: terraform-lab/${{ matrix.scenario }}
        run: terraform fmt -check
